### ISSUE TITLE
build.gradle check out of date, throws error in Android Studio

### ISSUE THREAD

**Issue by BBQSean** [manifoldjs/manifoldjs-cordova#11]
FYI - the Cordova/Android Gradle settings are out of date and throw an error. I believe this is the correct statement, changing the else if from 0.14.0+ to 2.1:

    // Switch the Android Gradle plugin version requirement depending on the
    // installed version of Gradle. This dependency is documented at
    // http://tools.android.com/tech-docs/new-build-system/version-compatibility
    // and https://issues.apache.org/jira/browse/CB-8143
    if (gradle.gradleVersion >= "2.2") {
        dependencies {
            classpath 'com.android.tools.build:gradle:1.5.0'
        }
    } else if (gradle.gradleVersion >= "2.1") {
        dependencies {
            classpath 'com.android.tools.build:gradle:2.1.0'
        }
    } else {
        dependencies {
            classpath 'com.android.tools.build:gradle:0.12.0+'
        }
    }
}

**Comment by boyofgreen** [comment]
Thanks Sean.  I'll take a look at this.  I am seeing a gradel build error in my stuff too.  It seems to build okay with just "manifoldjs package -p android " but I get an error in android studio.  Are you using Android Studio?  What version?

**Comment by BBQSean** [comment]
Thanks – am using Android Studio, latest version. On the plus side, my signed MVP app passed cert and was published on Google Play this AM. ;)
I did have to jump through some SDK Manager hoops. I wonder if it’s worth documenting? Happy to do.

**Comment by msrodri** [comment]
We could update ManifoldJS to include the correct mappings; however I noticed that the mappings @BBQSean specified above on this thread are currently out of date too in the latest version of Android Studio (which is currently 2.1.3), so if you use those mappings the issue still persists. These are the new mappings by the time of this writing (taken from http://tools.android.com/tech-docs/new-build-system/version-compatibility).

Android Gradle Plugin| Requires Gradle| 
------------------------ | ---------------- |
1.0.0 - 1.1.3|2.2.1 - 2.3|
1.2.0 - 1.3.1|2.2.1 - 2.9|
1.5.0|2.2.1+
2.0.0-2.1.2|2.10 - 2.13
2.1.3+|2.14.1+

Given that Android Studio will keep releasing new versions, these mappings might continue evolving. So adding these mappings in Manifold might have no effect in a near future.

Perhaps we should leave this as is and let Android Studio to fix this from the Gradle Sync window:

![image](https://cloud.githubusercontent.com/assets/924201/18487208/b43e4712-79ca-11e6-917c-502fbfd92163.png)

I'm planning to close this issue unless you have any other comments.

**Comment by boyofgreen** [comment]
closeing for now.
